### ISSUE TITLE
organizing tests!

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/partisan_dislocation#5]
@viveksahukar great work with the first pass at the code! Now to start re-organizing this as a software package and building up tests. 

First, note I make your `partisan_dislocation` file *the* partisan_dislocation.py file. We're using github so there's no need to keep versions differentiated by prefixes -- we can always get old versions of files. 

The next step is to get this packaged list a python package, and to develop our test suite. This will likely be very new for you, but hopefully also very educational. It's moving from "ad hoc analysis data science" to "software engineering data science". Basically, we want to do what this describes: https://packaging.python.org/tutorials/packaging-projects/ .

As you'll see, @Anshupriya2694 already started setting this up, so that's where our file structure came from. To run her tests, you move your terminal to the `partisan_dislocation` folder and run `python setup.py test` and it will run all the tests in the `tests/test_partisan_dislocation.py` folder. At the moment none of the tests run because they expect GeoDataFrames, and Anshupriya tested with GeoSeries, but hopefully that structure will make sense -- you're goal is to create some "toy" datasets with a known structure, then make sure the output matches what you expected. 

The goal here is to use these tests to provide guarantees that your code is doing what you expected, and to help you find some of the latent syntax problems in your code -- for example, I can already see this code won't run: 

![image](https://user-images.githubusercontent.com/9683693/86024637-3d06b100-b9fb-11ea-8901-2b4eef7786c0.png)

(The values in `points_to_add =  np.random.binomial(int(row[election + party]), p)` should just be `party`, not `election + party`, since that election prefix won't exist in all datasets.)

@viveksahukar Can you please add some tests that DO run successfully by Wednesday? I'd start by just writing some simple tests for `random_points_in_polygon` with `p=1` (so there's nothing stochastic about the number of points you generate)?

**Comment by nickeubank** [comment]
Some synthetic data: 

```
    df = gpd.GeoDataFrame({'D': [0, 1], 'R': [1, 0], 
                           'geometry': [Polygon([(0, 0), (1, 1), (0, 1)]),
                                        Polygon([(0, 0), (1, 1), (0, 1)])]})
    result = random_points_in_polygon(df, p=1)
    self.assertEqual(result["Dem"], pd.Series([0, 1], name='Dem'))
```

**Comment by viveksahukar** [comment]
Okay, I found what the problem is with random_points_in_polygon function:
the input is geodataframe so data type of each column is int64 and geometry for last one, but the data type of each column in output is object. 
Since I was doing string manipulations later on, the code ran and hence the test failed on random_points_in_polygon function.

So, the fix is to make sure we get the same type of input and output.. right?

**Comment by nickeubank** [comment]
Yup!

**Comment by nickeubank** [comment]
Or make sure you convert the columns inside the function before you run your string operations.

**Comment by viveksahukar** [comment]
Hi Nick,
I was able to run tests for random_points_in_polygon function on weekend and then when I resumed to write tests for other functions this morning, I reran unit tests but it gave me the following error. 
`Error
Traceback (most recent call last):
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\tests\test_partisan_dislocation.py", line 6, in <module>
    from partisan_dislocation import random_points_in_polygon
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\__init__.py", line 1, in <module>
    from .partisan_dislocation import random_points_in_polygon
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\partisan_dislocation.py", line 146, in <module>
    precinct_gdf, district_gdf = get_geodataframe("2008_presidential_precinct_counts.shp","US_cd114th_2014.shp" )
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\partisan_dislocation.py", line 15, in get_geodataframe
    precinct_gdf = gpd.read_file(fpath_precinct)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\geopandas\io\file.py", line 76, in read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\fiona\env.py", line 398, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\fiona\__init__.py", line 254, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\fiona\collection.py", line 154, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 484, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
Exception: ../data\2008_presidential_precinct_counts.shp: No such file or directory
-------------------- >> begin captured logging << --------------------
fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Starting outermost env
fiona.env: DEBUG: No GDAL environment exists
fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x000001E078690A90> created
fiona._env: DEBUG: Logging error handler pushed.
fiona._env: DEBUG: All drivers registered.
fiona._env: DEBUG: GDAL_DATA found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\gdal'.
fiona._env: DEBUG: PROJ_LIB found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\proj'.
fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x000001E078690A90>.
fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x000001E078690A90> with options {}
fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x000001E078690A90> options
fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x000001E078690A90>.
fiona._env: DEBUG: Error handler popped.
fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x000001E078690A90>.
fiona.env: DEBUG: Exiting outermost env
fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona.env: DEBUG: Starting outermost env
fiona.env: DEBUG: No GDAL environment exists
fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x000001E07AD28A20> created
fiona._env: DEBUG: Logging error handler pushed.
fiona._env: DEBUG: All drivers registered.
fiona._env: DEBUG: GDAL_DATA found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\gdal'.
fiona._env: DEBUG: PROJ_LIB found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\proj'.
fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x000001E07AD28A20>.
fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x000001E07AD28A20> with options {}
fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona._env: ERROR: ../data\2008_presidential_precinct_counts.shp: No such file or directory
fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x000001E07AD28A20> options
fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x000001E07AD28A20>.
fiona._env: DEBUG: Error handler popped.
fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x000001E07AD28A20>.
fiona.env: DEBUG: Exiting outermost env
fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x000001E07B425828>
fiona.env: DEBUG: Starting outermost env
fiona.env: DEBUG: No GDAL environment exists
fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x000001E07B425898> created
fiona._env: DEBUG: Logging error handler pushed.
fiona._env: DEBUG: All drivers registered.
fiona._env: DEBUG: GDAL_DATA found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\gdal'.
fiona._env: DEBUG: PROJ_LIB found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\proj'.
fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x000001E07B425898>.
fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x000001E07B425898> with options {}
fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x000001E07B425828>
fiona._env: ERROR: ../data\2008_presidential_precinct_counts.shp: No such file or directory
fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x000001E07B425828>
fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x000001E07B425898> options
fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x000001E07B425898>.
fiona._env: DEBUG: Error handler popped.
fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x000001E07B425898>.
fiona.env: DEBUG: Exiting outermost env
fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x000001E07B425828>
--------------------- >> end captured logging << ---------------------


Assertion failed

Assertion failed
E
======================================================================
ERROR: Failure: DriverError (../data\2008_presidential_precinct_counts.shp: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\tests\test_partisan_dislocation.py", line 6, in <module>
    from partisan_dislocation import random_points_in_polygon
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\__init__.py", line 1, in <module>
    from .partisan_dislocation import random_points_in_polygon
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\partisan_dislocation.py", line 146, in <module>
    precinct_gdf, district_gdf = get_geodataframe("2008_presidential_precinct_counts.shp","US_cd114th_2014.shp" )
  File "D:\nick_software_engg_project\partisan_dislocation\partisan_dislocation\partisan_dislocation.py", line 15, in get_geodataframe
    precinct_gdf = gpd.read_file(fpath_precinct)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\geopandas\io\file.py", line 76, in read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\fiona\env.py", line 398, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\fiona\__init__.py", line 254, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "C:\Users\vivek\Anaconda3\envs\geo\lib\site-packages\fiona\collection.py", line 154, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 484, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: ../data\2008_presidential_precinct_counts.shp: No such file or directory
-------------------- >> begin captured logging << --------------------
fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Starting outermost env
fiona.env: DEBUG: No GDAL environment exists
fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x000001E078690A90> created
fiona._env: DEBUG: Logging error handler pushed.
fiona._env: DEBUG: All drivers registered.
fiona._env: DEBUG: GDAL_DATA found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\gdal'.
fiona._env: DEBUG: PROJ_LIB found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\proj'.
fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x000001E078690A90>.
fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x000001E078690A90> with options {}
fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x000001E078690A90> options
fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x000001E078690A90>.
fiona._env: DEBUG: Error handler popped.
fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x000001E078690A90>.
fiona.env: DEBUG: Exiting outermost env
fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x000001E07ACF1CC0>
fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona.env: DEBUG: Starting outermost env
fiona.env: DEBUG: No GDAL environment exists
fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x000001E07AD28A20> created
fiona._env: DEBUG: Logging error handler pushed.
fiona._env: DEBUG: All drivers registered.
fiona._env: DEBUG: GDAL_DATA found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\gdal'.
fiona._env: DEBUG: PROJ_LIB found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\proj'.
fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x000001E07AD28A20>.
fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x000001E07AD28A20> with options {}
fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona._env: ERROR: ../data\2008_presidential_precinct_counts.shp: No such file or directory
fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x000001E07AD28A20> options
fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x000001E07AD28A20>.
fiona._env: DEBUG: Error handler popped.
fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x000001E07AD28A20>.
fiona.env: DEBUG: Exiting outermost env
fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x000001E07AD28AC8>
fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x000001E07B425828>
fiona.env: DEBUG: Starting outermost env
fiona.env: DEBUG: No GDAL environment exists
fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x000001E07B425898> created
fiona._env: DEBUG: Logging error handler pushed.
fiona._env: DEBUG: All drivers registered.
fiona._env: DEBUG: GDAL_DATA found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\gdal'.
fiona._env: DEBUG: PROJ_LIB found in environment: 'C:\\Users\\vivek\\Anaconda3\\envs\\geo\\Library\\share\\proj'.
fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x000001E07B425898>.
fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x000001E07B425898> with options {}
fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x000001E07B425828>
fiona._env: ERROR: ../data\2008_presidential_precinct_counts.shp: No such file or directory
fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x000001E07B425828>
fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x000001E07B425898> options
fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x000001E07B425898>.
fiona._env: DEBUG: Error handler popped.
fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x000001E07B425898>.
fiona.env: DEBUG: Exiting outermost env
fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x000001E07B425828>
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)

Process finished with exit code 1

Assertion failed

Assertion failed`

I created another environment and reran but no solution.
I googled and found that Fiona has issues reading geopandas file.
Is it the issue evident from the error log or am I doing something else wrong since the tests ran successfully on the weekend.

Thanks!

**Comment by nickeubank** [comment]
Your path is wrong

```
fiona.errors.DriverError: ../data\2008_presidential_precinct_counts.shp: No such file or directory
```

**Comment by nickeubank** [comment]
you gotta read your errors!

**Comment by viveksahukar** [comment]
I read that error and ran the original partisan file and confirmed that the data path is correct. The file ran and I could get all the final dataframes.

**Comment by nickeubank** [comment]
my guess is that the `\` is confusing the path. I don't think you can mix `/` and `\` in a path.

**Comment by nickeubank** [comment]
I don't see anything relevant pushed, so can't debug directly...

**Comment by viveksahukar** [comment]
```
    def test_random_points_in_polygon_simple_test(self):
        df = gpd.GeoDataFrame({'P2008_D': [0, 1], 'P2008_R': [1, 0],
                               'geometry': [Polygon([(0, 0), (1, 1), (0, 1)]),
                                            Polygon([(0, 0), (1, 1), (0, 1)])]})
        result = random_points_in_polygon(df, p=1)
        benchmark = pd.Series([0, 1], name='Dem')
        pd.testing.assert_series_equal(result["Dem"], benchmark)
```
For this test the error is 

```
AssertionError: Attributes of Series are different

Attribute "dtype" are different
[left]:  int32
[right]: int64
```

What data type shall I enforce in the dataframe returned by random_points_in_polygon? int64 or float...?

**Comment by nickeubank** [comment]
The dem column should be an int.

**Comment by viveksahukar** [comment]
Okay, the dem column should be int32 or int64?
Since, creating a test dataframe creates int64 by default..

**Comment by nickeubank** [comment]
64 is probably easier.

**Comment by viveksahukar** [comment]
Okay, changed that, writing next tests.

**Comment by viveksahukar** [comment]
When I'm passing null points in geometry as in the code below:
```
df = gpd.GeoDataFrame({'P2008_D': [0, 1], 'P2008_R': [1, 0],
                               'geometry': [Polygon([]),
                                            Polygon([])]})
result = random_points_in_polygon(df, p=1)
benchmark = pd.Series([], name='Dem', dtype='int64')
print(pd.Series.equals(result['Dem'], benchmark))
```

2 questions:
1. I have to specify the datatype in benchmark (int64) by default it is float64... should I include somewhere to assert that the data type is int64.
2. I'm getting  this error
```
<ipython-input-3-141320a09a36> in _make_random_points(number, polygon)
      2     #Generates number of uniformly distributed points in polygon
      3     points = []
----> 4     min_x, min_y, max_x, max_y = polygon.bounds
      5     i= 0
      6     while i < number:

ValueError: not enough values to unpack (expected 4, got 0)
```
Should I make sure that no empty points are passed?

**Comment by nickeubank** [comment]
on 2: yeah, don't use empty polygons.

On 1: Shouldn't be a problem -- the way we construct "dem" it should always be int64
